version: '3.7'
services:
  app:
    hostname: app
    container_name: polls-app
    build: .
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    links:
      - db
  db:
    container_name: polls-mysql
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./sql/scripts:/docker-entrypoint-initdb.d
      - ./sql/database:/var/lib/mysql
    restart: always
    env_file:
      - db.env
