version: '3.7'
services:
  app:
    container_name: polls-app
    build: .
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    env_file:
      - app.env
    links:
      - db
    networks:
      common:
        ipv4_address: 172.22.0.100
  db:
    container_name: polls-mysql
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./sql/scripts:/docker-entrypoint-initdb.d
      - ./sql/database:/var/lib/mysql
    restart: always
    env_file:
      - db.env
    networks:
      common:
        ipv4_address: 172.22.0.200


networks:
  common:
    ipam:
      config:
        - subnet: 172.22.0.0/16
    driver: bridge
