version: '3.7'
services:
  db:
    container_name: polls-mysql
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./sql/scripts:/docker-entrypoint-initdb.d
      - ./sql/database:/var/lib/mysql
    restart: always
    env_file:
      - config.env

