
version: 2.1
orbs:
  maven: circleci/maven@1.2.0
  docker: circleci/docker@1.5.0

jobs:
  start_sql_server: 
    docker:       
      - image: "ubuntu"
    steps:
      - run:
          name: Install docker-compose dependencies
          command: |
            apt update
            apt install -y curl tar jq
      - checkout
      - setup_remote_docker
      - docker/install-docker-compose
      - docker/install-docker
      - run:
          name: Setup config.env 
          command: |
            mv config.env.example config.env
            sed -i "s/<PASSWORD>/$MYSQL_ROOT_PASSWORD/g" config.env
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            cat config.env docker-compose.yml
            docker-compose up


            
workflows:
    test:
      jobs:
        - start_sql_server
        - maven/test:
            requires:
              - start_sql_server
