
version: 2.1
orbs:
  maven: circleci/maven@1.2.0
  docker: circleci/docker@1.5.0

jobs:
  start_sql_server: 
    docker:       
      - image: ubuntu
        environment:
          MYSQL_USER: root
          MYSQL_PASSWORD: $MYSQL_ROOT_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Install essential tools
          command: |
            set -x
            apt update
            apt-get install -y curl tar jq
      - docker/install-docker
      - docker/install-docker-compose
      - run:
          name: Start container and verify it is working
          command: |
            set -x

            mv config.env.example config.env
            sed -i "s/<PASSWORD>/$MYSQL_ROOT_PASSWORD/g" config.env
            ls -l

            mv ./src/main/resources/application.properties.example ./src/main/resources/application.properties
            sed -i "s/<mysql_password>/$MYSQL_ROOT_PASSWORD/g" ./src/main/resources/application.properties
            sed -i "s/<jwt-secret>/$JWT_SECRET/g" ./src/main/resources/application.properties

            cat ./src/main/resources/application.properties

            mkdir -p ./sql/database
            docker-compose up -d && 
            docker run --network container:polls-mysql \
            appropriate/curl --retry 10 --retry-delay 10 --retry-connrefused http://127.0.0.1:3306




            
workflows:
    test:
      jobs:
        - start_sql_server
        - maven/test:
            requires:
              - start_sql_server
        
