
version: 2.1
orbs:
  maven: circleci/maven@1.2.0

jobs:
  start_sql_server: 
    docker:       
      - image: "docker/compose"
    steps:       
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: docker-compose up -d  

            
workflows:
    test:
      jobs:
        - start_sql_server
        - maven/test:
            requires:
              - start_sql_server
