version: 2.1
orbs:
  docker-compose: parrable/docker-compose@1.0.1
  maven: circleci/maven@1.2.0

jobs:
  start_sql_server:
      machine:
        image: "ubuntu"
        docker_layer_caching: true
      steps:
        - setup_remote_docker:
            docker_layer_caching: true
        - docker-compose/up




            
workflows:
    test:
      jobs:
        - start_sql_server
        - maven/test:
            requires:
              - start_sql_server