
version: 2.1
orbs:
  maven: circleci/maven@1.2.0
  docker: circleci/docker@1.5.0

jobs:
  start_sql_server: 
    docker:       
      - image: circleci/mysql
        environment:
          MYSQL_USER: root
          MYSQL_PASSWORD: $MYSQL_ROOT_PASSWORD

    steps:
      - checkout
      - run:
          name: Start MYSQL
          command: |
            set -x
            apt install -y mysql-client
            mysql -u root -p $MYSQL_ROOT_PASSWORD < ./sql/scripts/init.sql
  


            
workflows:
    test:
      jobs:
        - start_sql_server
        
