
version: 2.1
orbs:
  maven: circleci/maven@1.2.0
  docker: circleci/docker@1.5.0

jobs:
  start_sql_server: 
    docker:       
      - image: "ubuntu"
    steps:
      - run:
          name: Install docker-compose dependencies
          command: |
            apt update
            apt install -y curl tar
      - checkout
      - setup_remote_docker
      - docker/install-docker-compose
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d
            docker run --network container:polls-mysql appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:3306

            
workflows:
    test:
      jobs:
        - start_sql_server
        - maven/test:
            requires:
              - start_sql_server
