version: 2.1

orbs:
  maven: circleci/maven@0.0.12
commands:
  start_mysql_server:
    description: "Start a docker container that will host the mysql server"
    steps:
      - run: docker-compose up -d
workflows:
  maven_test:
    jobs:
      - maven/test