
version: 2.1
orbs:
  maven: circleci/maven@1.2.0

jobs:
  start_sql_server: 
    docker:       
      - image: "alpine"
    steps:       
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            apk --no-cache add curl tar
            VER="19.03.8"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Install Docker Compose
          command: |
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.11.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Start container and verify it's working
          command: |
            set -x
            docker-compose up -d
            docker run --network container:polls-mysql appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:3306

            
workflows:
    test:
      jobs:
        - start_sql_server
        - maven/test:
            requires:
              - start_sql_server
