
version: 2.1
orbs:
  docker-compose: parrable/docker-compose@1.0.1
  maven: circleci/maven@1.2.0

jobs:
  start_sql_server: 
    docker:       
      - image: "docker/compose"
    steps:       
      - run: docker-compose up -d         

            
workflows:
    test:
      jobs:
        - start_sql_server
        - maven/test:
            requires:
              - start_sql_server
