
version: 2.1
orbs:
  docker: circleci/docker@1.5.0
  maven: circleci/maven@1.2.0
jobs:
  start_mysql_server:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker-compose up -d
          command: |
            docker-compose up
            
workflows:
  maven_test:
    jobs:
      - start_mysql_server
      - maven/test
