version: 2.1 # version de circleci à utiliser
orbs: # library
  maven: circleci/maven@1.2.0 # pouvoir mettre maven à disposition sur le cloud
  docker: circleci/docker@1.5.0 # pouvoir mettre maven à disposition sur le cloud


jobs: # début des actions
  start_sql_server:  # action principales qui va lancer des sous action
    machine: true
    steps: #étapes des actions à effectuer sur la vm ubuntu
      - checkout # git clone du projet
      - docker/install-docker # install docker
      - docker/install-docker-compose # et docker-compose
      - run: # lance les actions suivantes
          name: Start container and verify it is working
          command: |
            set -x
            mv db.env.example db.env
            sed -i "s/<MYSQL_PASSWORD>/$MYSQL_ROOT_PASSWORD/g" db.env
            ls -l

            mv ./src/main/resources/application.properties.example ./src/main/resources/application.properties
            sed -i "s/<MYSQL_PASSWORD>/$MYSQL_ROOT_PASSWORD/g" ./src/main/resources/application.properties
            sed -i "s/<JWT_SECRET>/$JWT_SECRET/g" ./src/main/resources/application.properties

            cat ./src/main/resources/application.properties
            cat ./db.env

            cat ./sql/scripts/init.sql
            mkdir -p ./sql/database

            docker-compose up --build -d db
            sleep 15
            mvn test

workflows:
    test:
      jobs:
        - start_sql_server
        
