
version: 2.1
orbs:
  maven: circleci/maven@1.2.0
  docker: circleci/docker@1.5.0

jobs:
  start_sql_server: 
    docker:       
      - image: ubuntu
        environment:
          MYSQL_USER: root
          MYSQL_PASSWORD: $MYSQL_ROOT_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - docker/install-docker-compose
      - run:
          name: Start container and verify it is working
          command: |
            set -x
            apt-get install -y curl tar
            mv config.env.example config.env
            sed -i "s/<PASSWORD>/$MYSQL_ROOT_PASSWORD/g" config.env
            cat config.env
            docker-compose up -d
            docker run --network container:polls-mysql \
            appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:3306




            
workflows:
    test:
      jobs:
        - start_sql_server
        - maven/test
        
