
version: 2.1
orbs:
  maven: circleci/maven@1.2.0
  docker: circleci/docker@1.5.0

jobs:
  start_sql_server: 
    docker:       
      - image: ubuntu
        environment:
          MYSQL_USER: root
          MYSQL_PASSWORD: $MYSQL_ROOT_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Install essential tools
          command: |
            set -x
            apt update
            DEBIAN_FRONTEND=noninteractive apt-get install -y curl tar jq maven
      - docker/install-docker
      - docker/install-docker-compose
      - run:
          name: Start container and verify it is working
          command: |
            set -x
            mv db.env.example db.env
            sed -i "s/<MYSQL_PASSWORD>/$MYSQL_ROOT_PASSWORD/g" db.env
            ls -l

            mv ./src/main/resources/application.properties.example ./src/main/resources/application.properties
            sed -i "s/<MYSQL_PASSWORD>/$MYSQL_ROOT_PASSWORD/g" ./src/main/resources/application.properties
            sed -i "s/<JWT_SECRET>/$JWT_SECRET/g" ./src/main/resources/application.properties

            cat ./src/main/resources/application.properties
            cat ./db.env

            mkdir -p ./sql/database
            mvn clean package -DskipTests
            docker-compose up -d
            echo "127.0.0.1	db" >> /etc/hosts
            mvn test






            
workflows:
    test:
      jobs:
        - start_sql_server
        
